This is a testharness.js-based test.
[FAIL] remove() while the file has an open writable fails
  promise_test: Unhandled rejection with value: object "ReferenceError: cleanup_writable is not defined"
Harness: the test ran to completion.

