This is a testharness.js-based test.
Found 3 FAIL, 0 TIMEOUT, 0 NOTRUN.
[FAIL] response.bytes() rejects if already aborted
  promise_test: Unhandled rejection with value: object "TypeError: response[bodyMethod] is not a function"
[FAIL] Fetch aborted & connection closed when aborted after calling response.bytes()
  promise_test: Unhandled rejection with value: object "TypeError: response[bodyMethod] is not a function"
[FAIL] Readable stream synchronously cancels with AbortError if aborted before reading
  assert_true: Cancel called sync expected true got false
Harness: the test ran to completion.

